export const ADD_EL = "ADD_EL";
export const CHANGE_OK = "CHANGE_OK";
export const DELETE_EL = "DELETE_EL";
export const CHANGE_QTY = "CHANGE_QTY";
export const INC_QTY = "INC_QTY";
export const DEC_QTY = "DEC_QTY";
export const CHANGE_SOMME ="CHANGE_SOMME";
export const CHANGE_POINT ="CHANGE_POINT";
export const INIT = "INIT";